apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: api-secrets
  namespace:  doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-auth
    namespace: doppler-operator-system
  project: mi-dev-stack
  config: dev
  managedSecret:
    name: api-secrets
    namespace: apps
    type: Opaque